services:
  - type: worker
    name: harshsinghrajawat369-cell/Music-X-Kshatriya- # Aap apna bot ka naam yahan likh sakte hain
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py # Apni main file ka naam check kar lein (main.py ya bot.py)
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: MONGO_DB_URI
        sync: false
        
